#:schema ../../Resource%20Schema/Course.json

title = "[title]"
description = """Written by [author], license [license]
Downloaded from [url] on [date]"""

# [[books]]
# label = "E-book"
# file  = ""
#
# [[books.chapters]]
# root = ""
#
# [[books.chapters.groups]]
# sections = [""]
